// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjpxpcmgduavednpmahk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcHhwY21nZHVhdmVkbnBtYWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mzk5NzksImV4cCI6MjA2NDIxNTk3OX0.FgZMbZCmCwxmXmrXwEdMuZ_TtYvvJHa4juMBdiV0RTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);